server:
  port: 6605
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: check
  profiles:
    active: product
  cloud:
    nacos:
#      server-addr: 114.132.92.175:8848
      server-addr: 10.1.32.242:8848
      discovery:
        server-addr: 10.1.32.242:8848
        namespace: ${spring.profiles.active}
        group: DEFAULT_GROUP
      config:
        namespace: ${spring.profiles.active}
        import-check:
          enabled: false
    sentinel:
      transport:
        dashboard: ${data.sentinel.dashboard.url}



---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:nacos:check.yml


---
spring:
  config:
    activate:
      on-profile: product
    import:
      optional:nacos:check.yml